# Generated by Django 2.0.1 on 2018-05-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='/media/profile_image/default.jpg', upload_to='profile_image'),
        ),
    ]
