# Generated by Django 2.0.1 on 2018-04-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favanime',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
