# Generated by Django 2.0.1 on 2018-04-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeweb', '0002_auto_20180407_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
    ]
