# Generated by Django 2.0.1 on 2018-04-07 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animeweb', '0003_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
