# Generated by Django 2.0.1 on 2018-04-12 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_userprofile_image'),
        ('animeweb', '0004_auto_20180407_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='accounts.UserProfile')),
                ('users', models.ManyToManyField(to='accounts.UserProfile')),
            ],
        ),
    ]
