# Generated by Django 2.0.1 on 2018-04-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeweb', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=models.CharField(default='', max_length=200),
        ),
    ]
