# Generated by Django 2.0.1 on 2018-05-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeweb', '0010_comment_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
