# Generated by Django 2.0.1 on 2018-05-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeweb', '0011_auto_20180504_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='popimage'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(null=True, upload_to='media/videos/', verbose_name=''),
        ),
    ]
