# Generated by Django 2.0.1 on 2018-05-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeweb', '0012_auto_20180505_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(null=True, upload_to='videos', verbose_name=''),
        ),
    ]
